-- Rozszerzenie bazy domowych środków o 15 dodatkowych metod
-- Data: 2025-12-15

INSERT INTO spray_products (
    name, active_substance, type, is_ecological,
    dosage_professional, dosage_2l, dosage_5l, dosage_notes,
    withdrawal_period,
    target_plants, target_pests,
    application_method, max_applications, interval_days,
    warnings, registered_poland
) VALUES
-- NAPARY I WYWARY
(
    'Napar z cebuli',
    'siarka, kwercetyna (naturalne)',
    'metoda_domowa',
    1,
    'Łupiny 3-4 cebul/1L',
    'Łupiny 6-8 cebul',
    'Łupiny 15-20 cebul',
    'Gotować łupiny w wodzie 15min, ostudzić, przecedzić. Rozcieńczyć 1:2 przed użyciem.',
    0,
    'pomidor, ogórek, kapusta, rośliny ozdobne',
    'mszyca, przędziorek, grzyby chorobotwórcze',
    'oprysk',
    NULL,
    7,
    'Naturalny preparat. Intensywny zapach może odstraszać niektóre szkodniki.',
    1
),
(
    'Napar z rumianku',
    'chamazulen, flawonoidy (naturalne)',
    'metoda_domowa',
    1,
    '50g suszonego/1L wody',
    '100g rumianku',
    '250g rumianku',
    'Zaparzać suszony rumianek wrzątkiem 30min, przecedzić. Stosować rozcieńczony 1:5.',
    0,
    'wszystkie warzywa, kwiaty, drzewa owocowe',
    'choroby grzybowe, wzmocnienie roślin młodych',
    'oprysk lub podlanie',
    NULL,
    10,
    'Łagodny fungicyd naturalny. Bezpieczny, można stosować często.',
    1
),
(
    'Napar z tytoniu',
    'nikotyna (toksyczna)',
    'metoda_domowa',
    0,
    '50g tytoniu/1L',
    '100g tytoniu',
    '250g tytoniu',
    'UWAGA: Toksyczny! Namoczyć tytoń w wodzie 24h, przecedzić. NIE stosować na tytoniu, pomidorach, paperce.',
    3,
    'kapusta, rzodkiewka (NIE pomidor, papryka!)',
    'mszyca, gąsienice, stonka',
    'oprysk',
    2,
    14,
    'TOKSYCZNY dla ludzi i pszczół! Unikać kontaktu ze skórą. Stosować ostatecznie. Szkodliwy dla pożytecznych owadów.',
    1
),
(
    'Wywar z liści pomidora',
    'tomatin, solanina (naturalne toksyny)',
    'metoda_domowa',
    1,
    '500g liści/1L',
    '1kg liści',
    '2.5kg liści',
    'Gotować pasierbki i dolne liście 20min. Ostudzić, przecedzić. Rozcieńczyć 1:4.',
    0,
    'kapusta, rzodkiewka, rzodkiew (NIE rośliny psiankowate!)',
    'mszyca, gąsienice kapustnika, pchełki',
    'oprysk',
    NULL,
    7,
    'Nie stosować na pomidorach, ziemniakach, papryce! Tylko na innych warzywach.',
    1
),
(
    'Wywar z łopianu',
    'inulina, taniny (naturalne)',
    'metoda_domowa',
    1,
    '300g liści/1L',
    '600g liści',
    '1.5kg liści',
    'Namoczyć świeże liście w wodzie 3 dni, mieszając codziennie. Rozcieńczyć 1:5.',
    0,
    'wszystkie warzywa, kwiaty',
    'mszyca, przędziorek',
    'oprysk',
    NULL,
    7,
    'Preparat fermentacyjny. Stosunkowo łagodny zapach.',
    1
),
(
    'Napar z wrotyczu',
    'tanacetyna, terpeny (naturalne)',
    'metoda_domowa',
    1,
    '300g świeżego/1L',
    '600g wrotyczu',
    '1.5kg wrotyczu',
    'Zalać wrzątkiem, napar 24h. Stosować bez rozcieńczania lub rozcieńczyć 1:2.',
    0,
    'wszystkie warzywa, owoce',
    'mszyca, przędziorek, mszyce',
    'oprysk',
    NULL,
    10,
    'Silnie pachnący. Odpędzający dla wielu szkodników.',
    1
),
(
    'Napar z skrzypu polnego',
    'kwas krzemowy, sole mineralne',
    'metoda_domowa',
    1,
    '100g suszonego/1L',
    '200g skrzypu',
    '500g skrzypu',
    'Namoczyć 24h, gotować 30min. Ostudzić, przecedzić. Rozcieńczyć 1:5 do oprysku.',
    0,
    'pomidor, ziemniak, ogórek, truskawka',
    'choroby grzybowe (zaraza, mączniak), wzmocnienie roślin',
    'oprysk',
    NULL,
    7,
    'Wzmacnia ściany komórkowe. Zapobiegawczy przeciw chorobom grzybowym.',
    1
),

-- ROZTWORY I MIESZANINY
(
    'Roztwór octu winnego',
    'kwas octowy (naturalny)',
    'metoda_domowa',
    1,
    '100ml octu/1L',
    '200ml octu',
    '500ml octu',
    'Ocet winny 5-6% rozcieńczony wodą. Stosować na chwasty punktowo, nie na uprawy!',
    0,
    'tylko na chwasty na alejkach, NIE na uprawach!',
    'chwasty jednoroczne',
    'aplikacja punktowa',
    1,
    NULL,
    'UWAGA: Niszczy wszystkie rośliny! Stosować TYLKO na chwasty z dala od upraw. Obniża pH gleby.',
    1
),
(
    'Woda z mydłem i alkoholem',
    'kwasy tłuszczowe + etanol',
    'metoda_domowa',
    1,
    '20g mydła + 50ml alkoholu/1L',
    '40g + 100ml spirytusu',
    '100g + 250ml spirytusu',
    'Rozpuścić mydło w ciepłej wodzie, dodać alkohol. Stosować świeżo przygotowane.',
    0,
    'rośliny doniczkowe, rośliny ozdobne',
    'mszyca, mączlik, przędziorek',
    'oprysk lub wycieranie liści',
    NULL,
    5,
    'Skuteczny na szkodniki. Może wysuszać liście - testować na małym fragmencie.',
    1
),
(
    'Olej rzepakowy + mydło',
    'kwasy tłuszczowe roślinne',
    'metoda_domowa',
    1,
    '10ml oleju + 5g mydła/1L',
    '20ml oleju + 10g mydła',
    '50ml oleju + 25g mydła',
    'Wymieszać olej z mydłem, dodać wodę. Dokładnie wstrząsnąć przed użyciem.',
    0,
    'wszystkie warzywa, owoce',
    'mszyca, mączlik, przędziorek',
    'oprysk',
    NULL,
    7,
    'Tworzy film olejowy duszący szkodniki. Spłukać przed zbiorem.',
    1
),
(
    'Soda kałczedonowa (krzemian sodu)',
    'krzemian sodowy',
    'metoda_domowa',
    1,
    '50ml kałczedonowej/1L',
    '100ml',
    '250ml',
    'Rozcieńczyć gotową sodę kałczedonową z apteki ogrodniczej. Zmienia pH powierzchni liści.',
    0,
    'winorośl, drzewa owocowe, pomidor',
    'mączniak, choroby grzybowe',
    'oprysk',
    NULL,
    10,
    'Alkaliczny pH hamuje grzyby. Stosować zapobiegawczo.',
    1
),

-- MECHANICZNE I FIZYCZNE
(
    'Pułapki na piwo',
    'fermentacja piwa (przywabianie)',
    'metoda_domowa',
    1,
    'Kubeczki z piwem wkopane do połowy',
    NULL,
    NULL,
    'Zakopać kubeczki do poziomu gleby, napełnić piwem w 1/3. Wymieniać co 2-3 dni.',
    NULL,
    'sałata, kapusta, truskawki, warzywa liściowe',
    'ślimaki nagie, ślimaki winniczki',
    'pułapki',
    NULL,
    NULL,
    'Ślimaki wpadają i toną. Sprawdzać codziennie rano. Może przyciągać ślimaki z daleka.',
    1
),
(
    'Pas lepowy',
    'żywica syntetyczna',
    'metoda_domowa',
    0,
    'Pas lepowy na pniu 50-100cm nad glebą',
    NULL,
    NULL,
    'Nałożyć pas lepowy na pień drzewa jesienią. Wymienić wiosną.',
    NULL,
    'drzewa owocowe (jabłoń, grusza, śliwa)',
    'mszyce przechodzące na drzewo, gąsienice pędraków',
    'pas fizyczny',
    1,
    NULL,
    'Mechaniczna bariera. Sprawdzać regularnie, uzupełniać uszkodzone miejsca.',
    1
),
(
    'Mulcz z kory',
    'materiał mechaniczny',
    'metoda_domowa',
    1,
    'warstwa 5-10cm',
    NULL,
    NULL,
    'Rozłożyć korę wokół roślin. Tłumi wzrost chwastów, utrzymuje wilgoć.',
    NULL,
    'wszystkie warzywa, krzewy, drzewa',
    'chwasty, utrzymanie wilgoci, ochrona korzeni',
    'mulczowanie',
    1,
    NULL,
    'Naturalna metoda. Poprawia strukturę gleby. Nie stosować przy młodych siewkach.',
    1
),
(
    'Netka ochronna',
    'materiał fizyczny',
    'metoda_domowa',
    1,
    'Okrycie 100% powierzchni',
    NULL,
    NULL,
    'Rozłożyć siatkę/włókninę nad grządkami. Zabezpieczyć brzegi kamieniami.',
    NULL,
    'kapusta, rzodkiewka, marchew, sałata',
    'śmietka kapuściana, pchełki, motyle',
    'bariera fizyczna',
    1,
    NULL,
    'Mechaniczna ochrona. Najskuteczniejsza metoda przy śmietce. Zdejmować na czas podlewania.',
    1
);
