-- Dodanie popularnych środków komercyjnych dostępnych w Polsce
-- Źródła: Allegro, sklepy ogrodnicze, research 2025
-- Data: 2025-12-15

INSERT INTO spray_products (
    name, active_substance, type, is_ecological,
    dosage_professional, dosage_2l, dosage_5l, dosage_notes,
    withdrawal_period,
    target_plants, target_pests,
    application_method, max_applications, interval_days,
    warnings, registered_poland
) VALUES

-- FUNGICYDY (choroby grzybowe)
(
    'Score 250 EC',
    'difenokonazol 250g/L',
    'fungicyd',
    0,
    '0.2ml/1L (0.02%)',
    '0.4ml',
    '1ml',
    'Systemiczny fungicyd. Stosować zapobiegawczo lub przy pierwszych objawach choroby.',
    14,
    'jabłoń, grusza, wiśnia, czereśnia, truskawka',
    'parch jabłoni, mączniak, szara pleśń',
    'oprysk',
    3,
    10,
    'Toksyczny dla organizmów wodnych. Okres karencji: 14 dni.',
    1
),
(
    'Switch 62.5 WG',
    'cyprodynil 375g/kg + fluodynil 250g/kg',
    'fungicyd',
    0,
    '1g/1L',
    '2g',
    '5g',
    'Granulat do sporządzania zawiesiny. Działa zapobiegawczo i interwencyjnie.',
    3,
    'truskawka, malina, winorośl, pomidor, ogórek',
    'szara pleśń, zgnilizna twardzikowa, mączniak',
    'oprysk',
    3,
    7,
    'Karencja 3 dni. Nie przekraczać 3 zabiegów w sezonie.',
    1
),
(
    'Amistar 250 SC',
    'azoksystrobina 250g/L',
    'fungicyd',
    0,
    '0.8ml/1L',
    '1.6ml',
    '4ml',
    'Fungicyd o działaniu systemicznym i powierzchniowym. Wysoka skuteczność.',
    14,
    'pomidor, ziemniak, cebula, marchew, truskawka',
    'zaraza ziemniaka, alternarioza, mączniak',
    'oprysk',
    3,
    10,
    'Nie stosować w mieszaninie z innymi środkami. Karencja: 14-21 dni zależnie od rośliny.',
    1
),
(
    'Ridomil Gold MZ Pepite 67.8 WG',
    'metalaksyl-M 3.8% + mankozeb 64%',
    'fungicyd',
    0,
    '2g/1L (0.2%)',
    '4g',
    '10g',
    'Granulat. Systemiczny + kontaktowy. Stosować zapobiegawczo podczas intensywnego wzrostu.',
    21,
    'ziemniak, pomidor, cebula, winorośl, ogórek',
    'zaraza ziemniaka, mączniak rzekomny, alternarioza',
    'oprysk',
    3,
    7,
    'Karencja: 21 dni. Silny środek - stosować zgodnie z etykietą.',
    1
),
(
    'Delan 700 WG',
    'ditianon 700g/kg',
    'fungicyd',
    0,
    '0.6g/1L',
    '1.2g',
    '3g',
    'Granulat do sporządzania zawiesiny. Działanie powierzchniowe, zapobiegawcze.',
    28,
    'jabłoń, grusza',
    'parch jabłoni, czarna plamistość',
    'oprysk',
    8,
    7,
    'Karencja: 28 dni. Stosować zapobiegawczo przed deszczem.',
    1
),

-- INSEKTYCYDY (szkodniki)
(
    'Calypso 480 SC',
    'tiaklopryd 480g/L',
    'insektycyd',
    0,
    '0.1ml/1L (0.01%)',
    '0.2ml',
    '0.5ml',
    'Systemiczny insektycyd o długim działaniu (21 dni). Bezpieczny dla pszczół po wyschnięciu.',
    7,
    'jabłoń, śliwa, wiśnia, ziemniak, rzepak',
    'mszyca, stonka ziemniaczana, owocówka, oprzędziki',
    'oprysk',
    2,
    21,
    'Działa w temp. >10°C. Karencja: 7 dni. Stosować po kwitnieniu.',
    1
),
(
    'Pirimor 500 WG',
    'pirymikarb 500g/kg',
    'insektycyd',
    0,
    '0.5g/1L',
    '1g',
    '2.5g',
    'Selektywny insektycyd na mszyce. Działa kontaktowo, żołądkowo i fumigacyjnie.',
    7,
    'ziemniak, burak, kapusta, marchew, ogórek, sałata, jabłoń',
    'mszyca (wszystkie gatunki)',
    'oprysk',
    2,
    10,
    'Skuteczny >15°C. Selektywny - oszczędza pożyteczne owady. Karencja: 7-14 dni.',
    1
),
(
    'Decis Mega 50 EW',
    'deltametryna 50g/L',
    'insektycyd',
    0,
    '0.05ml/1L',
    '0.1ml',
    '0.25ml',
    'Pyretroid o silnym działaniu kontaktowym i żołądkowym. Bardzo skuteczny.',
    7,
    'pszenica, burak, rzepak, ziemniak, jabłoń, śliwa',
    'mszyca, stonka, gąsienice, pchełki',
    'oprysk',
    2,
    14,
    'TOKSYCZNY dla pszczół i ryb! Stosować wieczorem. Działa <20°C. Karencja: 7 dni.',
    1
),
(
    'Polysect Ultra 005 SL',
    'acetamipryd 5g/L',
    'insektycyd',
    0,
    '1ml/1L',
    '2ml',
    '5ml',
    'Insektycyd systemiczny. Długie działanie. Dla roślin ozdobnych i użytkowych.',
    14,
    'rośliny ozdobne, rośliny doniczkowe, pomidor, ogórek',
    'mszyca, mączlik, wciornastki, mszyce wełniste',
    'oprysk',
    3,
    7,
    'Karencja: 14 dni. Stosować przy pierwszych szkodnikach.',
    1
);
