-- Dodanie domowych preparatów do bazy spray_products
-- Data: 2025-12-15

INSERT INTO spray_products (
    name, active_substance, type, is_ecological,
    dosage_professional, dosage_2l, dosage_5l, dosage_notes,
    withdrawal_period,
    target_plants, target_pests,
    application_method, max_applications, interval_days,
    warnings, registered_poland
) VALUES
(
    'Napar z czosnku',
    'siarka, allicyna (naturalne)',
    'metoda_domowa',
    1,
    '3-5 ząbków/1L wody',
    '6-10 ząbków',
    '15-25 ząbków',
    'Napar: rozgnieść czosnek, zalej wodą, odstaw 24h. Rozcieńczyć 1:5 przed użyciem. Stosować świeżo przygotowany.',
    0,
    'wszystkie warzywa, kwiaty, drzewa owocowe',
    'mszyca, przędziorek, mączniak',
    'oprysk',
    NULL,
    7,
    'Preparat naturalny, bezpieczny dla ludzi i pszczół. Może odstraszać zapachem. Stosować wieczorem.',
    1
),
(
    'Roztwór mydła szarego',
    'kwasy tłuszczowe (naturalne)',
    'metoda_domowa',
    1,
    '20g mydła/1L ciepłej wody',
    '40g mydła',
    '100g mydła',
    'Rozpuścić mydło w ciepłej wodzie, ostudzić. Można dodać 1 łyżkę oleju roślinnego dla lepszej przyczepności.',
    0,
    'wszystkie warzywa, kwiaty, rośliny ozdobne',
    'mszyca, mączlik szklarniowy, wciornastki',
    'oprysk',
    NULL,
    5,
    'Naturalny i bezpieczny. Spłukać przed spożyciem warzyw. Nie stosować w pełnym słońcu.',
    1
),
(
    'Napar z pokrzywy',
    'azot, mikroelementy (naturalne)',
    'metoda_domowa',
    1,
    '1kg pokrzywy/10L wody',
    '200g pokrzywy/2L',
    '500g pokrzywy/5L',
    'Fermentacja 10-14 dni (przykryć, mieszać codziennie). Rozcieńczyć 1:10 przed użyciem. Cuchnący ale skuteczny!',
    0,
    'wszystkie warzywa, kwiaty (wzmocnienie ogólne)',
    'mszyca, wzmocnienie odporności roślin, nawożenie dolistne',
    'oprysk lub podlanie',
    NULL,
    7,
    'Intensywny zapach podczas fermentacji. Może przyciągać muchy. Stosować w dni pochmurne.',
    1
),
(
    'Mleko z wodą (1:9)',
    'białka mleka (naturalne)',
    'metoda_domowa',
    1,
    'Mleko:woda 1:9',
    '200ml mleka + 1.8L wody',
    '500ml mleka + 4.5L wody',
    'Zwykłe mleko krowie rozcieńczone wodą. Stosować zapobiegawczo lub przy pierwszych objawach.',
    0,
    'ogórek, cukinia, dynia, kabaczek',
    'mączniak prawdziwy',
    'oprysk',
    NULL,
    7,
    'Całkowicie bezpieczne. Może zostawiać białe naloty - spłukać przed zbiorem. Nie stosować w upale.',
    1
),
(
    'Soda oczyszczona + olej',
    'wodorowęglan sodu (naturalne)',
    'metoda_domowa',
    1,
    '5g sody + 5ml oleju/1L wody',
    '10g sody + 10ml oleju',
    '25g sody + 25ml oleju',
    'Dokładnie wymieszać sodę z olejem roślinnym, dodać wodę. Używać świeżo przygotowanego roztworu.',
    0,
    'ogórek, cukinia, pomidor, róże',
    'mączniak prawdziwy, szara pleśń, choroby grzybowe',
    'oprysk',
    NULL,
    7,
    'Bezpieczny preparat. Zmienia pH powierzchni liści. Nie przesadzać z dawką.',
    1
);
